- name: Configure Mule-l1p.properties files
  local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/mule-l1p.properties.1"
    block: |
      dfsp-host={{ hostvars.dfsp1.ansible_host }}
      ilp-host={{ hostvars.dfsp1.ansible_host }}
      proxy-host={{ hostvars.dfsp1.ansible_host }}
      central-dir-env=mock
      central-dir-host={{ hostvars.switch.ansible_host }}
      central-dir-api.port=3000
      central-fraud-sharing-host={{ hostvars.switch.ansible_host }}
      central-fraud-sharing-api.port=3003
      mock-central-dir.host={{ hostvars.switch.ansible_host }}
      mock-central-dir.port=8088
      metrics.reporter.kafka.broker={{ hostvars.mgmt.ansible_host }}:9092
      environment=dfsp1-test
      metrics.reporter.environment=dfsp1-vagrant
      maxHttpThreadsActive=16
      maxHttpThreadsIdle=4

- local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/mule-l1p.properties.2"
    block: |
      dfsp-host={{ hostvars.dfsp2.ansible_host }}
      ilp-host={{ hostvars.dfsp2.ansible_host }}
      proxy-host={{ hostvars.dfsp2.ansible_host }}
      central-dir-env=mock
      central-dir-host={{ hostvars.switch.ansible_host }}
      central-dir-api.port=3000
      central-fraud-sharing-host={{ hostvars.switch.ansible_host }}
      central-fraud-sharing-api.port=3003
      mock-central-dir.host={{ hostvars.switch.ansible_host }}
      mock-central-dir.port=8088
      metrics.reporter.kafka.broker={{ hostvars.mgmt.ansible_host }}:9092
      environment=dfsp2-test
      metrics.reporter.environment=dfsp2-vagrant
      maxHttpThreadsActive=16
      maxHttpThreadsIdle=4

- local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf_switch/mule-l1p.properties.switch"
    block: |
      central-dir-env=mock
      mock-central-dir.host={{ hostvars.switch.ansible_host }}
      mock-central-dir.port=8088
      metrics.reporter.kafka.broker={{ hostvars.mgmt.ansible_host }}:9092
      environment=switch1-test
      metrics.reporter.environment=switch1-vagrant
      maxHttpThreadsActive=16
      maxHttpThreadsIdle=4

- name: Configure adapter-mapping.properties
  local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/adapter-mapping.properties.1"
    block: |
      mapping-dfsp-host={{ hostvars.dfsp1.ansible_host }}
      mapping-proxy-host={{ hostvars.dfsp1.ansible_host }}

- local_action:
    module: blockinfile
    create: yes
    dest: "artifacts/mule_artifacts/conf/adapter-mapping.properties.2"
    block: |
      mapping-dfsp-host={{ hostvars.dfsp2.ansible_host }}
      mapping-proxy-host={{ hostvars.dfsp2.ansible_host }}